# Generated by Django 4.1.5 on 2023-02-03 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account_books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("money", models.IntegerField(verbose_name="금액")),
                (
                    "expense_detail",
                    models.CharField(max_length=15, null=True, verbose_name="지출 내역"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("현금", "현금"), ("카드", "카드")],
                        default="현금",
                        max_length=2,
                        verbose_name="결제 수단",
                    ),
                ),
                (
                    "memo",
                    models.CharField(max_length=255, null=True, verbose_name="메모"),
                ),
                (
                    "account_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="account_books.accountbook",
                        verbose_name="가계부",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "db_table": "Expense",
            },
        ),
        migrations.CreateModel(
            name="ExpenseURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_url", models.URLField(verbose_name="공유 링크")),
                ("expired_at", models.DateTimeField(verbose_name="만료일")),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_urls",
                        to="expenses.expense",
                        verbose_name="지출",
                    ),
                ),
            ],
            options={
                "db_table": "ExpenseURL",
            },
        ),
    ]
