# Generated by Django 4.1.5 on 2023-02-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incomes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="income_detail",
            field=models.CharField(max_length=15, null=True, verbose_name="수익 내역"),
        ),
    ]
